### ISSUE TITLE
[Suggestion] Add lines between traits on specializations

### ISSUE THREAD

**Issue by DomGrieco** [madou/armory-app#192]
I think there should be something to make selected traits more visible. When looking at guardian traits the ones selected dont stand out that much vs ones that aren't selected. Maybe add a glow border around them?

![image](https://cloud.githubusercontent.com/assets/6556434/23532761/95a958ac-ff83-11e6-99ce-f4414082ac12.png)

**Comment by madou** [comment]
Maybe we can do something to get a smiliar effect to ingame with the traits being connected by a line

**Comment by madou** [comment]
http://i.imgur.com/Ux7B8yj.jpg

**Comment by DomGrieco** [comment]
pic is exactly what we need

**Comment by valento92** [comment]
This is nice QoL. :)
