### ISSUE TITLE
Add skill chain to embed skills

### ISSUE THREAD

**Issue by valento92** [madou/armory-app#232]
Have a way to show a skill chain embed within the tooltip. For example, auto-attacks tend to have a chain and it would be nice if you could display them one below another starting with 1st skill. Maybe a "gw2armory-skill-chain" with a list of ids?

**Comment by madou** [comment]
@valento92 this is more for just auto attack skills right?

for example when you keep using the skill it changes to another?

**Comment by valento92** [comment]
Not only autoattacks, Temporal Curtain is a mesmer focus skill which has a sequence. So sequence skills join the team.
