### ISSUE TITLE
Add SPA support for GW2AEmbeds

### ISSUE THREAD

**Issue by SkippDoe** [madou/armory-app#304]
Your documentation is very bare-boned, and provides no details on implementation other than statically assigning data attributes on page load. How would I refresh/update or call the embeds manually once I fetch character data from the GW2 API?

I'm using Vue.js for all the other stuff so all the data placeholders are initially empty which makes the embeds also empty on page load. The data gets loaded into the placeholders a few seconds after page load and GWEmbeds obviously don't refresh automatically.

Mind adding this little detail to your documentation?

Thnx!

**Comment by madou** [comment]
hi, thanks for making an issue!

yeah the documentation could be better - but it basically shows what the current capabilities of the embeds have right now. atm embeds aren't made to work well with SPAs (i will make an issue to add support).

one work around you could use is to use the vue lifecycle hook to add the embed script (`/gw2aEmbeds.js`) to your document after your component has rendered. that will get the embeds rendering, however they won't be cleaned up when you transition to another route, so it's a potential memory leak until the user ventures away from the site or does a page refresh.

**Comment by SkippDoe** [comment]
Yup, that worked! I don't worry about memory leaks since Vue handles only the character sheet and assigning all the binding from the API json to various DOM elements. Meaning, all other navigation always refreshes the page (not a single-page application).

Maybe you could simply add an .update() or .refresh() method so people can just call that on a specific container.

Thnx again

**Comment by madou** [comment]
sweet! what you making? :)

yeah i think that will work. probably need to add two methods, `bootstrap` and `cleanup` or something.

**Comment by SkippDoe** [comment]
At the moment, a simple web-app for the guild that will manage the Tyria scavenger hunt contestants. The idea is to provide "seasons" of 10 riddles/hints that guildies will need to solve. Each riddle will point them to a specific place/npc/item in the world which they need to find. Submitting responses into the app will validate the answer and award appropriate points to the member.

We're planing on various season rewards like ingame gold, skins, gem rewards, and even other game keys. :)

And since I was planning on making a guild armory anyway - i'm just gonna cram everything together since it's their characters that are doing the scavenger hunt anyway :)

This way our raid leaders get a simple way of inspecting people.

**Comment by madou** [comment]
ah ok cool :)

fyi gw2armory supports some decent guild integrations :)

**Comment by SkippDoe** [comment]
Anything extra apart from the embeds? I mean - i personally have a profile there, but i don't want to tell people to manage their accounts on another site so i can show the info on a guild site where they need to make a new account again.

**Comment by madou** [comment]
yeah multiple accounts is annoying.

the armory though shows all connected data, for example: https://gw2armory.com/g/Starbuck

you can see the guild leader (katubug), if you are apart of the guild you can see message of the day and stats, and logs. 

and you can also see all members and characters who are apart of the guild (and click through and see their pages too).

**Comment by madou** [comment]
this can be done by using https://github.com/madou/armory-component-ui
