### ISSUE TITLE
Embeds not displaying multiple optional icons

### ISSUE THREAD

**Issue by valento92** [madou/armory-app#342]
Per this example:
`<div data-armory-embed="skills" data-armory-ids="-1,-1,-1,13012,13113"></div>`

It's not showing 3 optional slots for some reason.

![issue](https://user-images.githubusercontent.com/6351070/30240287-3d589444-953b-11e7-8294-3084691b2c07.png)

**Comment by madou** [comment]
Yeah it wasn't really made to support multiple.

For now I'd suggest just using multiple embeds.

**Comment by valento92** [comment]
@madou I changed that, the way things are nested to resolve skill ids made this a nightmare haha but it's working for now.

**Comment by madou** [comment]
ok.

we'd have to rethink the system if we want to support multiple blank spots all with unique text.

**Comment by madou** [comment]
this has been fixed in the new version of armory-embeds.
