### ISSUE TITLE
Embed images containing extra whitespace vertically

### ISSUE THREAD

**Issue by valento92** [madou/armory-app#345]
From the image below, the class is `ky5a`, it wraps a div containing the icon itself. Due to its line-height being set to 1.5, it adds whitespace below, much like a padding-bottom (my thought originally). Setting line-height to 0 solves this.

![found](https://user-images.githubusercontent.com/6351070/30529937-77d6f116-9c10-11e7-92d7-a3e784a715a4.png)

**Comment by madou** [comment]
Fixed in the new release of armory-embeds.
